//
//  MainModels.swift
//  DemoNote
//
//  Created by Hoang Tung on 2/4/20.
//  Copyright (c) 2020 Hoang Tung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
  // MARK: Use cases
  
  enum Something {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
  
  enum TypeList {
    struct Request {
      
    }
    
    struct Response {
      var typeList: [TypeNote]
    }
    
    struct ViewModel {
      struct DisplayedType {
        let imageName: String
        let title: String
        let count: String
      }
      
      var displayedTypes: [DisplayedType]
    }
  }
}

struct TypeNote {
  let imageName: String
  let title: String
  let count: Int
}

let fakeNotes = [
      TypeNote(imageName: "calendar", title: "Hôm nay", count: 0),
      TypeNote(imageName: "timer", title: "Lịch dự kiến", count: 0),
      TypeNote(imageName: "box", title: "Tất cả", count: 0),
      TypeNote(imageName: "tag", title: "Đã gắn cờ", count: 0)
]
