//
//  NewNoteModels.swift
//  DemoNote
//
//  Created by Hoang Tung on 2/6/20.
//  Copyright (c) 2020 Hoang Tung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewNote
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
  
  enum Title {
    struct Request {
    }
    
    struct Response {
      let title: String?
    }
    
    struct ViewModel {
      let title: String?
      let color: UIColor
    }
  }
}
