//
//  NewNoteViewController.swift
//  DemoNote
//
//  Created by Hoang Tung on 2/6/20.
//  Copyright (c) 2020 Hoang Tung. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NewNoteViewController: UIViewController, HasCustomView {
  typealias CustomView = NewNoteView
  
  var titleNote: String?
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
  }
  
  // MARK: View lifecycle
  
  override func loadView() {
    let customView = CustomView()
    view = customView
    setupNavigation()
    displayTitle()
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
    setupNavigation()
  }
  
  override func viewWillAppear(_ animated: Bool) {
    setupNavigation()
  }
  
  // MARK: setup NavigationBar
  
  func setupNavigation() {
//    navigationController?.navigationBar.topItem?.title = "Danh sách"
  }
  
  // MARK: Do something
  
  func setTitle() {
    
  }
  
  func displayTitle() {
    customView.titleLabel.text = titleNote
    switch titleNote {
      case "Hôm nay":
        customView.titleLabel.textColor = .systemBlue
      case "Lịch dự kiến":
        customView.titleLabel.textColor = .systemOrange
      case "Tất cả":
        customView.titleLabel.textColor = .systemGray
      case "Đã gắn cờ":
        customView.titleLabel.textColor = .systemRed
      default:
        customView.titleLabel.textColor = .systemGreen
    }
  }
}
